### ISSUE TITLE
Request tools.min.js

### ISSUE THREAD

**Issue by avin** [manubb/Leaflet.PixiOverlay#1]
Great extention! Thank you! Can you also share original code of `tools.min.js` that uses in examples?

**Comment by manubb** [comment]
Thank you. The content of `tools.min.js` is listed in `package.json` (in scripts -> build:doc). Everything is freely available except circles.js. Are you asking for this particular file?

**Comment by avin** [comment]
searching for `window.solveCollision` original function. Seems it is in your `circles.js`

**Comment by manubb** [comment]
You'll find it [there](https://github.com/manubb/Leaflet.PixiOverlay/blob/master/docs_src/js/circles.js).

**Comment by avin** [comment]
@manubb, thank you!
