### ISSUE TITLE
Texture inside polygon

### ISSUE THREAD

**Issue by vk207** [manubb/Leaflet.PixiOverlay#10]
Is there any possibilities to draw texture in polygon with out changing the background color

**Comment by manubb** [comment]
I'a not a pixi master but maybe that masking is the feature that you need:
http://pixijs.io/examples/#/demos/masking.js
or
http://pixijs.io/examples/#/demos/mask-render-texture.js

**Comment by manubb** [comment]
I will close this issue. If your problem is stil unsolved, consider asking help [here](http://www.html5gamedevs.com/forum/15-pixijs/).
