### ISSUE TITLE
Pixi Ticker availability

### ISSUE THREAD

**Issue by icithis** [manubb/Leaflet.PixiOverlay#13]
I noticed there are methods for getContainer, getRenderer, etc. However if I want to animate something without map interaction (like the change in weather over time) there's no getTicker. Is there a way to add this to the project, instead of using the renderer on a loop?

**Comment by manubb** [comment]
I did some testing yesterday and some reflexion is needed on this to improve the API but you can try something like:
```js
...
pixiLayer.addTo(map);

var ticker = new PIXI.ticker.Ticker();
ticker.add(function(timestamp) {
    markerSprites.forEach(function(markerSprite) {
    markerSprite.rotation -= 0.03 * timestamp;
  });
  pixiLayer.redraw();
});
ticker.start();
```
Anyway, can you provide a basic JSFiddle describing your usercase? That would really help me to clarify my thoughts.
