### ISSUE TITLE
Doesn't work click event on map on Mobile

### ISSUE THREAD

**Issue by emehmet** [manubb/Leaflet.PixiOverlay#16]
Hi,
Doesn't work click event on map on Mobile. 
How can I use?

**Comment by manubb** [comment]
What is your device? os? browser? Are you experiencing this on any homepage demo?

**Comment by emehmet** [comment]
Excuse me. I tested your examples. https://manubb.github.io/Leaflet.PixiOverlay/leaflet-quickstart.html. And My Phone is LG G4 (android). Browser is Chrome V:65

**Comment by manubb** [comment]
The other examples with interactivity are:
Largest [US cities](https://manubb.github.io/Leaflet.PixiOverlay/us-cities.html).
French presidential 2017 election results: [first round](https://manubb.github.io/Leaflet.PixiOverlay/t1.html).
Can you tell me if the problem also occurs on them?

**Comment by emehmet** [comment]
Yes. I get same result for all examples too.

**Comment by manubb** [comment]
I have commited a fix for the demos. Can you check and tell me if the problem is solved?
Thanks.

**Comment by emehmet** [comment]
I checked very basic demo, Largest US cities (1000 animated markers), French cities (36700 animated markers) and French presidential 2017 election results. All demos worked properly except (very basic demo) on Android phone version. Sometimes very basic demo works. Sometimes not. I tried to understand how work. I think there is a difference between clicking on the map and clicking on the marker. When I tangent the marker on the screen, the popup opens. But when I click directly on the marker, it does not always pop up. The same result applies to polygons. 
Thanks for your great job.

**Comment by manubb** [comment]
Glad to read that almost of demos are fixed! Can you recheck the very basic demo, please? (I needed some times to fix this one. I fell into the hell of leaflet events and pixi.js events...)

**Comment by emehmet** [comment]
Okay. Everything looks good. Demos is working properly on Android. Thanks for your great job and great project.

**Comment by manubb** [comment]
Thanks for reporting!
