### ISSUE TITLE
PixiOverlay use a lot of GPU

### ISSUE THREAD

**Issue by Mennter** [manubb/Leaflet.PixiOverlay#20]
Hi, I have a problem with PixiOverlay. When I ran this example https://manubb.github.io/Leaflet.PixiOverlay/animated-markers.html,  my GPU goes 0% to 90%.
I'm running this example in Chorme 71.0.3578.98. 
Thank you and i look forward to you answer

**Comment by Mennter** [comment]
With task manager for Windows 10

**Comment by manubb** [comment]
I do not have any W10 computer to test on. Can you compare the GPU load with some pixi demos:
https://pixijs.io/examples
?
For example:
- https://pixijs.io/examples/#/basics/container-pivot.js
-https://pixijs.io/examples/#/demos/blendmodes.js

And maybe the bunny demo with 1000 bunnies:
https://pixijs.io/bunny-mark
?

Can you also report the GPU load on the animated-markers demo when setting the browser window size to 800x600? (I'm expecting animated-markers to use twice GPU resources compared to 1000 bunnies demo.)

Can you also tell me if the problem occurs in other browsers? 
Thanks for your help.

**Comment by manubb** [comment]
Thanks for you report. Considering that the GPU load is 65% on the bunny demo with 1000 items, i do not see any specific problem with Leaflet.PixiOverlay and i'm going to close the issue. Consider reporting a bug on the pixi repo if you think there is a pixi problem here.
