### ISSUE TITLE
smooth animation on circles

### ISSUE THREAD

**Issue by pere** [manubb/Leaflet.PixiOverlay#23]
hi, I was wondering if it could be possible to do smooth animation on circles/sprites as I did for hits using D3.js

[https://drive.google.com/file/d/10d5L_zR-MyQf1H9CLDg1wKcvnPQd5mvW/view?usp=sharing](https://drive.google.com/file/d/10d5L_zR-MyQf1H9CLDg1wKcvnPQd5mvW/view?usp=sharing)

With just some circles D3 works fine. Then, browser collapses.
I am completely new to Pixi.js, I guess it should be done changing the scale. I managed to change it, but not smoothly at all. There is something similar to D3.js for animating? thanks in advance

**Comment by manubb** [comment]
I have added a demo. Not exactly what you are describing but it should give you ideas on how to solve your problem:
https://manubb.github.io/Leaflet.PixiOverlay/scaled-animated-markers.html
(Scale animation is triggered when  zoom changes.)
You'll find the sources in the docs folder.

**Comment by pere** [comment]
Ideal to start figuring out, thanks a lot
