### ISSUE TITLE
add popup on a marker

### ISSUE THREAD

**Issue by vito2005** [manubb/Leaflet.PixiOverlay#25]
Hello! Thank you for ur plagin, it's amaizing.
Is it possible to add a popup when i click a marker?
I mean right over a marker, not in fix div in a header or another place of a page
Thank u.

**Comment by manubb** [comment]
Hello.
Yes it is! This is done in this [demo](https://manubb.github.io/Leaflet.PixiOverlay/leaflet-quickstart.html).

**Comment by vito2005** [comment]
Thank u, is it work when I draw 10000 markers?

**Comment by manubb** [comment]
Probably, yes.
