### ISSUE TITLE
No layer update during flyTo

### ISSUE THREAD

**Issue by maxel-inc** [manubb/Leaflet.PixiOverlay#27]
When map.flyTo or map.flyToBounds pixi scene updated only on last frame. During "flying" no animation at all. The same problem with fast zoom scrolling.

Why?

**Comment by manubb** [comment]
The pixi scene is updated on `moveend` by default so this is expected behavior.
You can try to add this listener:
```js
map.on('move', pixiLayer._update, pixiLayer);
```
However, ideally, the listener should only be added during the `flyTo` animation.
I do not understand what you mean:
> The same problem with fast zoom scrolling.

Can you clarify, please?

**Comment by manubb** [comment]
Update: you can filter `move` events in the following way:
```js
map.on('move', (e) => {
  if (e  && e.flyTo) {pixiLayer._update(e);}
});
```
Can you tell if this is working correctly? (If so, i will consider adding this to the lib as default behavior.)

**Comment by manubb** [comment]
I've added support for redraws during `flyTo` animation in v1.8.0:
```js
var pixiOverlay = L.pixiOverlay(drawCb, pixiContainer, {
  shouldRedrawOnMove: e => e.flyTo
});
```
I do not think that anything can be done for refreshing during fast mousewheel scroll.
