### ISSUE TITLE
Polygons little random offsets

### ISSUE THREAD

**Issue by avin** [manubb/Leaflet.PixiOverlay#3]
Found strange behavior on move map. When you have high zoom, you can see that polygons have random offset when you drag map. Markers do not have this problem. Seems some rounding happens in pixi.js lib, not sure where dig in

you can check this on demo https://manubb.github.io/Leaflet.PixiOverlay/leaflet-quickstart.html

**Comment by manubb** [comment]
This is indeed a precision issue. Commit 18d5c5cb05ed fixes the [demo](https://manubb.github.io/Leaflet.PixiOverlay/leaflet-quickstart.html). More info can be found [here](https://github.com/pixijs/pixi.js/issues/4032#issuecomment-301828053).

**Comment by avin** [comment]
that solution works fine! thank you very much
