### ISSUE TITLE
pixiJS v5

### ISSUE THREAD

**Issue by iofirag** [manubb/Leaflet.PixiOverlay#31]
this library working also with pixi 5.0?

**Comment by iofirag** [comment]
can you please upload an example? i didnt success using is. :/

**Comment by manubb** [comment]
Hello.
Yes, the lib supports both pixi 4 and pixi 5. The simple demos should work with pixi 5 with almost no changes and, if i remember correctly, the browser console shows what needs to be updated.

**Comment by iofirag** [comment]
with your example i'm getting 
> ERROR TypeError: Cannot set property '_parentID' of undefined

"leaflet": "1.5.1"
"pixi.js": "^5.0.4"
"leaflet-pixi-overlay": "^1.8.1"

**Comment by iofirag** [comment]
as i can see,
your code works great with pixi.js <= v4.8.7, 
(So fail with latest pixi.js v5.0.4)

Works OK -
**"pixi.js": "^4.8.7"**
"leaflet": "1.5.1"
"leaflet-pixi-overlay": "^1.8.1"
[Demo with pixi.js-v4.8.7](http://plnkr.co/edit/rA4sJA?p=preview)

Fail -
**"pixi.js": "^5.0.4"**
"leaflet": "1.5.1"
"leaflet-pixi-overlay": "^1.8.1"
[Demo with pixi.js-v5.0.4](https://plnkr.co/edit/87xy1fH1ofVTywwIDdeT?p=preview)

**Comment by manubb** [comment]
Ok. Your code is using my patched version of ParticuleContainer and this patch does not work with pixi@5.
You can either use pixi@4 or try to use plain pixi@5 or write a new patch for pixi@5. I won't be able to look into this in near future.

**Comment by bradley-varol** [comment]
I had a `PIXI.loaders is not defined` error with Pixi 5 and downgrading to 4.8.9 resovled it!
