### ISSUE TITLE
_renderer is not destroyed

### ISSUE THREAD

**Issue by cokicm** [manubb/Leaflet.PixiOverlay#32]
_renderer created at line [106](https://github.com/manubb/Leaflet.PixiOverlay/blob/3dccef66de8b441ed7de4e1221aabc877d7b99e9/L.PixiOverlay.js#L106) is not destroyed. On creating multiple PixiOverlays, video memory allocated at this place leaks.

If the field is destroyed by calling _renderer.destroy(), GPU memory is freed.

Probably PixiOverlay should have its own destroy() method that should destroy _renderer and possibly _auxRenderer as well.

**Comment by manubb** [comment]
Thanks for reporting. I will fix this but i need some time to think about it.

**Comment by manubb** [comment]
It has taken more time than expected but it is included in leaflet-pixi-overlay@1.9.3.
