### ISSUE TITLE
Markers not showing when hardware acceleration is off

### ISSUE THREAD

**Issue by kras95** [manubb/Leaflet.PixiOverlay#34]
The title says it all. I happened to have hardware acceleration off and was wondering why the markers weren't loading on the map. I'm not sure who in the right mind would turn hardware acceleration off, but just bringing this to your attention.

This occurs in the latest version of Google Chrome, "One million markers" demo.

**Comment by manubb** [comment]
This is correct: the one million markers demo currently requires WebGL. The reason for that is that i only patched the WebGL part of: https://github.com/manubb/Leaflet.PixiOverlay/blob/master/docs/js/MarkerContainer.js
Anyway, performance should be very bad in canvas and i won't fix this!
