### ISSUE TITLE
Collision Issue 

### ISSUE THREAD

**Issue by nerdherdwa** [manubb/Leaflet.PixiOverlay#39]
Awesome work on this looks great when rendering out data points and has solved an issue with rendering 5k+ markers with leaflet. The issue im having is that im using the demo for the french cities as i like the way the markers are rendered, but when it comes to process collision on my datasets it is either crashing the browser or takes a very long time to calculate. And im assuming its the density of the points that is crashing my browser. As i have some datasets that its rendering 126k markers in about 33s but then i have a dataset of only 2k and the browser crashes during the quadtrees calculation. The largest dataset that i have passed through is 477K markers which actually renders the points but takes 12578s to complete the process. Any suggestions on how to improve the processing of these points faster or more efficiently. I want to continue to use the code in my application but struggling to find a solution to improve the processing of the points.

some examples of the results that im getting, though the first one did take some time to render (477K markers)

<img width="765" alt="GLD_WOD_Data_Zoom" src="https://user-images.githubusercontent.com/6523964/72441194-338ae300-37e5-11ea-9ee1-9c511c35f9d2.png">

<img width="549" alt="CTD_WOD_Data" src="https://user-images.githubusercontent.com/6523964/72441214-3d144b00-37e5-11ea-8e03-6ad7d47ed8e1.png">

<img width="958" alt="MBT_WOD_Data" src="https://user-images.githubusercontent.com/6523964/72441234-49000d00-37e5-11ea-8ea7-666a76ec233f.png">

**Comment by manubb** [comment]
Hi. Nice pictures!
Can you try to decrease the size of the markers? (i agree though that this is not a good solution...)

**Comment by manubb** [comment]
Can you upload the 2k dataset that crashes the fix collision function? (so that i can test it and see what can be done).

**Comment by nerdherdwa** [comment]
[mrb.zip](https://github.com/manubb/Leaflet.PixiOverlay/files/4084781/mrb.zip)

Here is zip file of the json file with the data that crashes browser when attempting to create zoom level between 5 and 16. I can get it to render the page if i only put one zoom level but not really a solution considering the density of the points.

![WOD_Data_MRB_Zoom5_10598pts](https://user-images.githubusercontent.com/6523964/72704630-537b2780-3b94-11ea-82ce-072a6a4ed48d.png)
![WOD_Data_MRB_Zoom8_809pts_(-23 72501,10089844)](https://user-images.githubusercontent.com/6523964/72704636-58d87200-3b94-11ea-9290-32e27f2c0ffb.png)
![WOD_Data_MRB_Zoom8_4582pts_(-10 90895,93 60339)](https://user-images.githubusercontent.com/6523964/72704638-58d87200-3b94-11ea-81cf-f3877e4ce5ad.png)
![WOD_Data_MRB_Zoom9_2000pts_(-8 8339,163 37151)](https://user-images.githubusercontent.com/6523964/72704639-58d87200-3b94-11ea-87d4-be3ec01336c9.png)

**Comment by nerdherdwa** [comment]
Any feedback on the density of points when trying to calculate the collision positions

**Comment by manubb** [comment]
Hi. Sorry for the delay but i think that i found the root of the problem.
Can you tell if the problem happens randomly on the 2k dataset? (Sometimes the computation succeeds in a few seconds ans sometimes it fails after a much longer times.)

**Comment by manubb** [comment]
I've pushed a new `circles.js` file that fixes the crashes with the 2k dataset. Can you check on your side?

**Comment by manubb** [comment]
I've added a demo with the 2k dataset [here](https://manubb.github.io/Leaflet.PixiOverlay/issue39.html).

**Comment by nerdherdwa** [comment]
@manubb no worries the areas where i had issues with small amounts of points rendering due to density of the points, now seems fixed when using the new circle.js file, they render all the points with out the browser crashing. It was always crash would only render once i reduced the number of points to around 500

7k points rendered at a position was previously crashing

![7000pts](https://user-images.githubusercontent.com/6523964/75512158-79190d80-5a2b-11ea-8083-a958398a89dc.png)

Thanks for your help my next option was cluster at the postgis database api and then only render one cluster point out for those areas that had issues

**Comment by manubb** [comment]
The collision fix function was not designed to handle efficiently many points sharing same position. If you still have performance issue with the 477k dataset, you can consider doing some preprocessing to fix collisions on the same position clusters.
