### ISSUE TITLE
Black Overlay "background"

### ISSUE THREAD

**Issue by git-toni** [manubb/Leaflet.PixiOverlay#4]
Hi, 

I'd love to use this little plugin, so thanks for publishing it! : )
Unfortunately I am facing a black overlay, and then the primitives are rendered on top of this black "background". I guess it's something really simple but can't seem to find it.
Please see an example in this [codepen](https://codepen.io/git-toni/pen/oGjyrP?editors=0010). I tried with different tiles and also altering it via CSS, but no luck.
Thanks!

**Comment by manubb** [comment]
This seems to be a pixi.js bug in 4.4.x versions. Please use latest pixi.js@4.5.5.

**Comment by git-toni** [comment]
Thanks, fixed!

**Comment by KovacicB** [comment]
Hi,

I am facing this issue as well - this time with new versions of libraries. I have "forked" the repository and locally rewrote the code so that it works with new versions.
Leaflet: 1.9.3
Pixi.js: 7.1.1

Any ideas?
