### ISSUE TITLE
not working on mobile

### ISSUE THREAD

**Issue by gnesher** [manubb/Leaflet.PixiOverlay#40]
Not sure if anything can be done about this really - but when viewing any of the examples (such as basic demo / 1000 US Cities) the markers take forever to render / re-render when you zoom or pan.

Tested on an Android/Chrome using the latest OS and ~2 years old phone.

**Comment by manubb** [comment]
On a 4Go Redmi Note 5, the demos are fine. Are you sure that webgl is enabled?
(It is enabled if you see the webgl logo on: https://manubb.github.io/Leaflet.PixiOverlay/t1.html)

**Comment by gnesher** [comment]
I'm using a Xiaomi Mi A1 which is a little older/weaker.
The map renders and at some point I also see the markers, it's just inconsistent (webgl is enabled).
In any case, it seems fine now, maybe there was some connectivity issue - my apologies.
