### ISSUE TITLE
Integration with Existing Leaflet Canvas

### ISSUE THREAD

**Issue by sgentile** [manubb/Leaflet.PixiOverlay#6]
I'm using the utils.getRender inside my code (see below), however, I'm also using leaflet canvas circle markers.  When I add my pixiContainer, it adds a second canvas.   I end up losing my interactive sprint mousedown events since I have 2 canvas's instead of a shared canvas.

Is there a way to have pixiOverlay use the existing map canvas instead of creating its own ?

Thanks

```
var renderer = utils.getRenderer();
...
renderer.render(container);
```

**Comment by manubb** [comment]
A `canvas` element cannot be used with both 2d and webgl contexts. IMHO, your best option is to draw your circle markers in the pixiOverlay layer.
