### ISSUE TITLE
Transparent attribute is deprecated in PixiJs v6 and should be replaced with backgroundAlpha.

### ISSUE THREAD

**Issue by sgokul2700** [manubb/Leaflet.PixiOverlay#69]
![image](https://user-images.githubusercontent.com/53429356/134652183-87150c42-0461-45e4-9983-9f9c1e510ef5.png)
The transparent property in options has been deprecated in v6 of PixiJs. Is it possible to replace the transparent with backgroundAlpha in order to remove the deprecation warning?
![image](https://user-images.githubusercontent.com/53429356/134652538-2bd3fd5b-09e9-4b72-8aab-9449702c255d.png)

**Comment by manubb** [comment]
It is fixed in leaflet-pixi-overlay@1.8.4.
