### ISSUE TITLE
Multiple Overlays Issue

### ISSUE THREAD

**Issue by vk207** [manubb/Leaflet.PixiOverlay#7]
I need an urgent help regarding pixi Overlay. i am using two layers  with some markers .. i only could select the markers of last layer. I would need to select both select layer's marker
![image](https://user-images.githubusercontent.com/5058934/34871253-f2ce46fa-f7b2-11e7-9154-4fa4be50bb2d.png)
The html generated
![image](https://user-images.githubusercontent.com/5058934/34871332-4453dabc-f7b3-11e7-9640-0ae177f7e82f.png)

**Comment by manubb** [comment]
If you want to use Pixi events for selection, the simplest solution is to use only one pixi-overlay instance. If you need to show/hide the layers, you can set the markers in two containers: greenMarkerContainer  and brownMarkerContainer and add/remove those containers to/from the main pixi container.
Please give me more precision if i misunderstand something.

**Comment by vk207** [comment]
I think u are correct. Let me check . do u have any link ?. 
Thanks Manuel for the quick reply 👍

**Comment by manubb** [comment]
Something like:
```js
const pixiContainer = new PIXI.Container();
const greenMarkerContainer = new PIXI.Container();
const brownMarkerContainer = new PIXI.Container();
pixiContainer.addChild(greenMarkerContainer);
pixiContainer.addChild(brownMarkerContainer);
...
const pixiOverlay = L.pixiOverlay(function(utils) {
  const container = utils.getContainer();
  const renderer = utils.getRenderer();
  ...
  renderer.render(container);
}, pixiContainer);
pixiOverlay.addTo(map);
...
You can remove a layer with:
```js
pixiContainer.removeChild(greenMarkerContainer);
```
See [Pixi.doc](http://pixijs.download/v4.6.2/docs/PIXI.Container.html).

**Comment by vk207** [comment]
Thanks Manuel 👍

**Comment by vk207** [comment]
Hai manuel,
   Could you please give me an explanation regarding how the green/brown MarkerContainer adding in the Overlay. because the parent layer is added in Layer and didn't used green/brown MarkerContainer nowhere else .
In my application many types of markers are came based on the user. Eg :- if i select 2 users then map should show all customers under 2 users ... and if i select 3 more total 5 user's customers need to show.

In the above example , you just add the child container to the parent and parent container is adding to Layer. then how we know drawing which child container is active while drawing time?

**Comment by manubb** [comment]
In order to control visibility of `pixiContainer` children, you can either set `visibillity` property on children or add/remove children from `pixiContainer`. See [here](http://pixijs.download/dev/docs/PIXI.Container.html) for detailed documentation. After updating the scene, you can trigger a redraw of pixiOverlay layer with:
```js
pixiOverlay._update();
```

**Comment by manubb** [comment]
I'm closing this issue. Reopen it if you need to but please provide detailed informations on your problem.

**Comment by vk207** [comment]
Hi,
    Still have the issue of  Mouse events in multiple L.PixiLeafletOverlay in an application. i can click only one overlay layer . 
eg:- 
1st Overlay has have some polygons .
2nd Overlay has some sprite markers .
i can click only on sprite markers .

And i need to keep those are different overlays because to change the display order [z-index] based on the user cases.

Please help me to find a exact solution to propagate events through overlays. will be better if you have demo code of exact implementation. 

![image](https://user-images.githubusercontent.com/5058934/36425782-db1477e4-166d-11e8-9be7-f0fe11dbadca.png)

Green points are sprite markers [ The red ones are clicked ], the below white is polygon

**Comment by vk207** [comment]
Hi ,
you are correct if it drawing both at a time . Here not in that situation. 
user can add layers dynamically one by one when ever he needs.
and also remove layers.

My doubt regarding your code is 

pixiContainer.addChild(polygonContainer);
pixiContainer.addChild(markerContainer);

You added those childs into parent pixi container thats OK.

But  in the below code you take the **parent pixiContiner**  to draw

const pixiOverlay = L.pixiOverlay(function(utils) {
  const container = utils.getContainer(); // <- **is it marker container or polygoncontainer or parent** 
  const renderer = utils.getRenderer();
  ...
  // your drawing code
  ....
  renderer.render(container);
}, pixiContainer);**<- mentioned parent Container . then how the draw happens in specific child container ( marker or polygon)**

**Comment by manubb** [comment]
I have updated my previous comment. The idea is to add/remove/move children of the `pixiContainer` depending on your needs.  Then calling `pixiOverlay.redraw()` will redraw the complete scene.

**Comment by vk207** [comment]
But i checked with this code  by one layer , the total markers are drawing inside the parent container [pixiContainer]. didnt  inside Child Container[markerContainer].

**Comment by manubb** [comment]
I'm not sure i understand but you have to add your markers in the `markerContainer` and the polygons in the `polygonContainer` in the `drawCallback` function.

**Comment by vk207** [comment]
Thats Fine. but how we can dynamically push new layers. in this code we are writing all at once.
