### ISSUE TITLE
BUG: Library doesn't work with latest version of leaflet.

### ISSUE THREAD

**Issue by mitow7821** [manubb/Leaflet.PixiOverlay#77]
Library isn't working with leaflet 1.9 version. In 1.8 it was working as expected.
I am unable to use L.pixiOverlay:

![image](https://user-images.githubusercontent.com/34492112/191918385-52d639b2-017b-4dfa-b3b5-75af0a21ae4b.png)

**Comment by manubb** [comment]
Thanks for reporting. Will have a look at it. Not sure it's a bug though ;-)

**Comment by manubb** [comment]
It seems that leaflet@1.9.2 solves the issue. Can you check it?

**Comment by adelriosantiago** [comment]
Yes @manubb leaflet@1.9.2 solves the issue. It looks like it was an issue in leaflet. Thanks.
