### ISSUE TITLE
Polygon border/ graphics line Scaling

### ISSUE THREAD

**Issue by vk207** [manubb/Leaflet.PixiOverlay#8]
I am drawing around 50K polygon. using graphics object. is there any oprions to scale polygon borders[line] while zoom in /out. redrawing is very bad idea in this case ;(

**Comment by manubb** [comment]
I understand that you would like to have line/polygon borders width independant of zoom level. Unfortunately, this is not a simple geometry transformation.
You can either recompute/redraw at each zoom change (more CPU, less RAM) or cache the scene at each zoom level (less CPU, more RAM).

**Comment by vk207** [comment]
I think we can change the  properties of graphics data and render again. i just changed the colors of polygon in that way ....
Am i correct

**Comment by manubb** [comment]
Your target is unclear to me. Can you describe precisely what you are trying to achieve? A screenshot could also help.

**Comment by manubb** [comment]
I will close this issue. If your problem is still unsolved, consider asking help [here](http://www.html5gamedevs.com/forum/15-pixijs/).
