### ISSUE TITLE
What is included in the example.min.js at many-markers example?

### ISSUE THREAD

**Issue by dnl4** [manubb/Leaflet.PixiOverlay#85]
[example.min.js](https://manubb.github.io/Leaflet.PixiOverlay/js/example.min.js) at [many-markers demo](https://manubb.github.io/Leaflet.PixiOverlay/many-markers.html)

This file has some other files included in it, like leaflet.js, and others that I wasn't able to find. 

Which are they?

**Comment by manubb** [comment]
You can see this in `package.json`:
```
./node_modules/leaflet/dist/leaflet-src.js
./node_modules/graph-draw/dist/graph-draw-bundle.js
./node_modules/leaflet-hash/leaflet-hash.js
./node_modules/leaflet.photon/leaflet.photon.js
./node_modules/pixi.js/dist/pixi.js ./L.PixiOverlay.js -m -c -o ./docs/js/example.min.js 
```
