### ISSUE TITLE
examples

### ISSUE THREAD

**Issue by nigelPam** [manubb/Leaflet.PixiOverlay#88]
I am struggling a little with example.min.js.  This seems to replace various functions in L.PixiOverlay.js. Is there an unminimised version, so I can debug or trace some issues? is there some additional functionality in the code?

For some reason the layer is not being rendered when first drawn, and I need to see what is going on.

**Comment by manubb** [comment]
Hi. You can find what is bundled in example.min.js in package.json in the "scripts" section ("build:doc").

**Comment by nigelPam** [comment]
OK, I think I am following. So example.min.js includes minimised version of L.PixiOverlay.js, but also graph-draw, leaflet.photon, leaflet-hash etc.

So in the example french-cities.html, we have

	<script src="js/example.min.js"></script>
	<script src="js/tools.min.js"></script>

and L.PixiOverlay.js is not needed because it is already  bundled in example.min.js

**Comment by nigelPam** [comment]
BTW, the problem I am having is that markers are not appearing until I do something like a mouseover or change window size. Probably because I am not using the loader, because it was not compatible with the version of leaflet I was using (1.7.1) .

Yes, I have confirmed this.

BTW I am using the latest pixi release which has pixi sprite events like mouseover, which means I don;t need some of the pixi overlay functionality to find pixi sprites?

**Comment by nigelPam** [comment]
Just to follow up. I checked and  example.min.js does have the latest leaflet 1.7.1. So I just need to load example.min.js and everything will be there.

There is another comment I will make on a separate issue which may help somebody.
