### ISSUE TITLE
PIXI v7 events

### ISSUE THREAD

**Issue by nigelPam** [manubb/Leaflet.PixiOverlay#91]
PIXI v7 deprecates renderer.plugins.interaction - just a warning at present, it probably has various implications. as the interaction manager is deprecated.

I doubt this is a 5 min job to fix.

https://github.com/pixijs/pixijs/wiki/v7-Migration-Guide

**Comment by manubb** [comment]
It should be supported in leaflet-pixi-overlay@1.9.3 which was released today.
